# See:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    # Group minor and patch updates.  Major updates will be updated individually.
    groups:
      github-actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
